spring:
  activate:
    on-profile: production

  output:
    ansi:
      enabled: NEVER

  grpc:
    server:
      reflection:
        enabled: false

logging:
  level:
    root: "warn"

  structured:
    format:
      console: ecs
